### ISSUE TITLE
Log In Feature: Scenario: Charlie enters correct credentials

### ISSUE THREAD

**Issue by ghost** [nectR-Tutoring/nectr#121]
Given Charlie is registered to nectr
  Given charlie is on nectr site
  When charlie clicks on menu button
  And charlie clicks on login
  Then charlie is redirected to Login page
  When Charlie enters his correct username
  And Charlie enters his correct password
  And Charlie clicks on sign in
  #TODO: Charlie can not be redirected to dashboard because there is nothing named
  #dashboard. Need to rethink this part of scenario
  #Then charlie is redirected to dashboard

**Comment by MikeAy90** [comment]
Let's ignore this scenario on the log in feature. I created two new scenarios which are much more detailed, "Brandon enters correct credntials and antoher one for incorrect.

Scenario: Brandon enters correct credentials
  Given Brandon is registered to nectr
  And Brandon's username is Cashmeousside
  And Brandon's password is Howboudat
  And Brandon is on home page of nectr
  And Brandon is not signed in
  When Brandon clicks "Menu"
  And Brandon clicks "Log In" button
  Then Brandon is redirected to "Sign In" page
  And title of the page is "Login"
  And page contains an h1 whos text is "Sign In"
  When Brandon clicks on username text field
  And Brandon enters "Cashmeousside"
  And Brandon clicks on password text field
  And Brandon enters "Howboudat"
  And Brandon cicks "Sign In" button
  Then Brandon is redirected to "Dashboard" page whos title contains "Cashmeousside"
  And profile "username" is "Cashmeousside"

Scenario: Brandon tries to sign in again but enters incorrect credentials
  Given Brandon is registered to nectr
  And Brandon's username is Cashmeousside
  And Brandon's password is Howboudat
  And Brandon is on home page of nectr
  And Brandon is not signed in
  When Brandon clicks "Menu"
  And Brandon clicks "Log In" button
  Then Brandon is redirected to "Sign In" page
  And title of the page is "Login"
  And page contains an h1 whos text is "Sign In"
  When Brandon clicks on username text field
  And Brandon enters "Cashmeousside"
  And Brandon clicks on password text field
  And Brandon enters "Howboudatt"
  And Brandon cicks "Sign In" button
  Then Brandon is presented with an alert
  And username text field is cleared
  And password text field is cleared

**Comment by ghost** [comment]
I'll run this test tomorrow
