### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by valec4** [nectR-Tutoring/nectr#14]
@morej6

**Comment by morej6** [comment]
Not specific enough.

**Comment by valec4** [comment]
Home page has a Navigtion bar that allows users to to go home/become a tutor/sign up/ login.
“As a visitor, I want to use the navigation bar to go home to become a tutor to sign up or login.”

**Comment by valec4** [comment]
![screen shot 2017-04-03 at 11 09 59 am](https://cloud.githubusercontent.com/assets/25773813/24616114/304c185c-185e-11e7-996c-12e16affa882.png)

**Comment by valec4** [comment]
App logo on the left , //"Become a Tutor", "Sign up" and  "Log In"

**Comment by valec4** [comment]
https://github.com/nectR-Tutoring/nectr-website/commit/4aa218e90addbc2b811b4ef7d37e7d79ffbbf7cd
