### ISSUE TITLE
Courses Offered Navigation row

### ISSUE THREAD

**Issue by valec4** [nectR-Tutoring/nectr#34]
Home page has a navigations row that will show the user a list of general courses being offered.
“As a visitor, I want to view general courses being offered in order to get tutored.”

**Comment by valec4** [comment]
![screen shot 2017-04-03 at 11 06 39 am](https://cloud.githubusercontent.com/assets/25773813/24615963/b97d5218-185d-11e7-88fc-f292b407b895.png)

**Comment by valec4** [comment]
" MATH / SCIENCE / COMPUTER SCIENCE / ENGLISH / LANGUAGES / MORE "

**Comment by valec4** [comment]
More tab should go to find a tutor page.

**Comment by morej6** [comment]
7651697e3c97d4b72697c72141a95ddbc7c71f26
