### ISSUE TITLE
How It Works Links

### ISSUE THREAD

**Issue by MikeAy90** [nectR-Tutoring/nectr#37]
Home page has a "how it works link"
“As a visitor, I want to click on the How It Works link so i can learn how necR works."

**Comment by MikeAy90** [comment]
<img width="264" alt="how it works" src="https://cloud.githubusercontent.com/assets/25318385/24618400/ee29afc8-1864-11e7-983b-97aa40e57a4f.png">

**Comment by valec4** [comment]
https://github.com/nectR-Tutoring/nectr-website/commit/34eb88fd322f75f61322b090554e235f51a68fb7
