### ISSUE TITLE
How it works page

### ISSUE THREAD

**Issue by MikeAy90** [nectR-Tutoring/nectr#42]
Page which shows how nectR works

**Comment by enoc2k43** [comment]
[how it works.zip](https://github.com/nectR-Tutoring/nectr/files/925072/how.it.works.zip)

**Comment by ghost** [comment]
@enoc2k43 Uploaded the zip file of the how it works page as a complete page. This needs to be adapted to the site and merged into site.

**Comment by ghost** [comment]
@MikeAy90 Can you make an issue for this page in the board today?

**Comment by valec4** [comment]
pushed and added @enoc2k43 content of how it works page.
